#!/bin/sh

cp -r ~/.config/i3 ~/.git/i3-rice/.config
cp -r ~/.config/termite ~/.git/i3-rice/.config
cp -r ~/.config/polybar ~/.git/i3-rice/.config
cp -r ~/.config/rofi ~/.git/i3-rice/.config
cp -r ~/.bin ~/.git/i3-rice
cp -r /etc/pacman.d/hooks/* ~/.git/i3-rice/pacman/hooks
cp ~/Pictures/.wallpapers/* ~/.git/i3-rice/wallpapers
cp ~/.config/compton.conf ~/.git/i3-rice/.config
cp ~/.zshrc ~/.git/i3-rice
cp ~/.vimrc ~/.git/i3-rice
cd ~/.git/i3-rice
git add .
git commit
git push
